ALTER TABLE images ADD COLUMN IF NOT EXISTS status VARCHAR(32) NOT NULL DEFAULT 'ready';
ALTER TABLE images ADD COLUMN IF NOT EXISTS error TEXT NULL;
CREATE INDEX IF NOT EXISTS idx_images_status ON images(status);
